

;;   ;; (progn (message (random 10000))
;;   ;;        (message type)))

;; ((equal type '"COMMAND_TYPE_PRESS"))
;; ((equal type '"COMMAND_TYPE_CLOSE_TAB")
;;  (print "close tab"))
;; ((equal type '"COMMAND_TYPE_NEXT_TAB")
;;  (next-buffer))
;; ((equal type '"COMMAND_TYPE_PREVIOUS_TAB")
;;  (previous-buffer))
;; ((equal type '"COMMAND_TYPE_SWITCH_TAB")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_OPEN_FILE_LIST")
;;  (spacemacs-layouts/non-restricted-buffer-list-helm))
;; ((equal type '"COMMAND_TYPE_OPEN_FILE")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_UNDO")
;;  (undo))
;; ((equal type '"COMMAND_TYPE_REDO")
;;  (redo))
;; ((equal type '"COMMAND_TYPE_SCROLL")
;;  (message "scroll")
;;  (debug)
;;  (zz-scroll-half-page-down))
;; ((equal type '"COMMAND_TYPE_STYLE")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_GO_TO_DEFINITION")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_TOGGLE_BREAKPOINT")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_START")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_PAUSE")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_STOP")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_SHOW_HOVER")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_CONTINUE")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_STEP_INTO")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_STEP_OVER")
;;  (print "switch tab"))
;; ((equal type '"COMMAND_TYPE_DEBUGGER_INLINE_BREAKPOINT")
;;  (print "switch tab"))
;;  ((equal type '"COMMAND_TYPE_SELECT")
;;   (serenade-select-region-evil (+ 1 (ht-get* message-command "cursor"))
;;                                (+ 1 (ht-get* message-command "cursorEnd")))))
;; (serenade-send-completed))))

(provide 'serenade-builtin-commands)
