
(if (boundp 'spacemacs-version) 
    (progn (spacemacs/set-leader-keys (kbd "av") 'serenade-mode) 
           (spacemacs/set-leader-keys (kbd "al") 'serenade--log-open-log) 
           (spacemacs/set-leader-keys (kbd "as") 'serenade-helm-commands) 
           (spacemacs/set-leader-keys (kbd "ac") 'serenade--log-clear-log) 
           (serenade-define-speech 'global "open buffer <name>" 'switch-to-buffer) 
           (setq serenade--spacemacs-global-defaults '(;;
                                                       ( "copy" .   serenade--copy-selection ) 
                                                       ( "cut" .   serenade--cut-selection ) 
                                                       ( "paste" .   serenade--paste ) 
                                                       ( "undo" .   serenade--undo ) 
                                                       ( "redo" .   evil-redo ) 
                                                       ( "close tab" . delete-window  ) 
                                                       ( "save"  . save-buffer  ) 
                                                       ( "create tab" .
                                                         split-window-right-and-focus)
                                                       ( "next tab" . next-buffer  ) 
                                                       ( "previous tab" . previous-buffer) 
                                                       ( "open file list" .
                                                         spacemacs-layouts/non-restricted-buffer-list-helm)
                                                       ( "open file" . nil  ) 
                                                       ( "scroll" . zz-scroll-half-page-down  ) 
                                                       ( "go to definition" .
                                                         spacemacs/jump-to-definition  )
                                                       ( "switch tab" . nil  ) 
                                                       ( "debug toggle breakpoint" . nil) 
                                                       ( "style" . nil) 
                                                       ( "start debug" . nil  ) 
                                                       ( "pause debug" . nil  ) 
                                                       ( "stop debug" . nil  ) 
                                                       ( "show hover" . nil) 
                                                       ( "continue debug" . nil  ) 
                                                       ( "debug step into" . nil  ) 
                                                       ( "debug step over" . nil) 
                                                       ( "debug inline breakpoint" . nil))) 
           (serenade-global-set-speech serenade--spacemacs-global-defaults)
           ;; (serenade-global-set-speech '(;;
           ;;                                 ( "copy" .   serenade--copy-selection )
           ;;                                 ( "cut" .   serenade--cut-selection )
           ;;                                 ;; ( "paste" .   serenade--paste )
           ;;                                 ( "undo" .   serenade--undo )
           ;;                                 ( "redo" .   evil-redo )
           ;;                                 ( "close tab" . delete-window  )
           ;;                                 ( "save"  . save-buffer  )
           ;;                                 ( "create tab" . split-window-right-and-focus  )
           ;;                                 ( "next tab" . next-buffer  )
           ;;                                 ( "previous tab" . previous-buffer)
           ;;                                 ;; ( "switch tab" . nil  )
           ;;                                 ( "open file list" .
           ;;                                   spacemacs-layouts/non-restricted-buffer-list-helm)
           ;;                                 ;; ( "open file" . nil  )
           ;;                                 ;; ( "undo" .  undo  )
           ;;                                 ( "scroll" . zz-scroll-half-page-down  )
           ;;                                 ;; ( "style" . nil)
           ;;                                 ( "go to definition" . spacemacs/jump-to-definition  )
           ;;                                 ;; ( "debugger toggle breakpoint" . nil)
           ;;                                 ;; ( "debugger start" . nil  )
           ;;                                 ;; ( "debugger pause" . nil  )
           ;;                                 ;; ( "debugger stop" . nil  )
           ;;                                 ;; ( "debugger show hover" . nil)
           ;;                                 ;; ( "debugger continue" . nil  )
           ;;                                 ;; ( "debugger step into" . nil  )
           ;;                                 ;; ( "debugger step over" . nil)
           ;;                                 ;; ( "debugger inline breakpoint" . nil)
           ;;                                 ))
           ))
(provide 'serenade-spacemacs)
