
(if (boundp 'spacemacs-version) 
    (progn (spacemacs/set-leader-keys (kbd "av") 'serenade-mode) 
           (spacemacs/set-leader-keys (kbd "al") 'serenade--log-open-log) 
           (spacemacs/set-leader-keys (kbd "as") 'serenade-helm-commands) 
           (spacemacs/set-leader-keys (kbd "ac") 'serenade--log-clear-log) 
           (serenade-define-speech 'global "open buffer <name>" 'switch-to-buffer) 
           (setq serenade--spacemacs-global-defaults '(;;
                                                       ( "undo" .   serenade--undo ) 
                                                       ( "redo" .   serenade--redo ) 
                                                       ( "close tab" . delete-window  ) 
                                                       ( "save"  . save-buffer  ) 
                                                       ( "create tab" .
                                                         split-window-right-and-focus)
                                                       ( "next tab" . next-buffer  ) 
                                                       ( "previous tab" . previous-buffer) 
                                                       ( "open file list" .
                                                         spacemacs-layouts/non-restricted-buffer-list-helm)
                                                       ( "open file" . nil  ) 
                                                       ( "scroll" . zz-scroll-half-page-down  ) 
                                                       ( "go to definition" .
                                                         spacemacs/jump-to-definition  )
                                                       ( "switch tab" . nil  ) 
                                                       ( "debug toggle breakpoint" . nil) 
                                                       ( "style" . nil) 
                                                       ( "start debug" . nil  ) 
                                                       ( "pause debug" . nil  ) 
                                                       ( "stop debug" . nil  ) 
                                                       ( "show hover" . nil) 
                                                       ( "continue debug" . nil  ) 
                                                       ( "debug step into" . nil  ) 
                                                       ( "debug step over" . nil) 
                                                       ( "debug inline breakpoint" . nil))) 
           (setq serenade--spacemacs-user-defaults '(;;
                                                     ( "show tree" . treemacs))) 
           (serenade-global-set-speech serenade--spacemacs-global-defaults) 
           (serenade-global-set-speech serenade--spacemacs-user-defaults)))
(provide 'serenade-spacemacs)
